import { v2 as cloudinary } from 'cloudinary';
import { unlink } from 'fs/promises';

// Configure Cloudinary if credentials are set in environment
const isConfigured = 
  process.env.CLOUDINARY_CLOUD_NAME && 
  process.env.CLOUDINARY_API_KEY && 
  process.env.CLOUDINARY_API_SECRET;

if (isConfigured) {
  cloudinary.config({
    cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
    api_key: process.env.CLOUDINARY_API_KEY,
    api_secret: process.env.CLOUDINARY_API_SECRET,
  });
}

/**
 * Uploads a local file to Cloudinary.
 * If Cloudinary keys are missing, returns the local static server path.
 * Automatically deletes the temporary local file if uploaded to Cloudinary.
 * 
 * @param localFilePath Local file path where Multer saved the file
 * @param filename Filename generated by Multer
 * @returns The final URL to store in the database
 */
export const uploadToCloudinary = async (
  localFilePath: string,
  filename: string
): Promise<string> => {
  if (!isConfigured) {
    console.log('[Cloudinary] Credentials missing. Falling back to local static server path.');
    return `/uploads/${filename}`;
  }

  try {
    const result = await cloudinary.uploader.upload(localFilePath, {
      folder: 'myarea_connect_complaints',
      resource_type: 'image',
    });
    
    // Clean up local temporary file after successful Cloudinary upload
    try {
      await unlink(localFilePath);
    } catch (cleanupErr) {
      console.error('[Cloudinary] Failed to delete local temp file:', cleanupErr);
    }

    return result.secure_url;
  } catch (error: any) {
    console.error('[Cloudinary] Upload failed, falling back to local static URL:', error.message);
    return `/uploads/${filename}`;
  }
};
